### ISSUE TITLE
Module not logging users with numerical 'name'

### ISSUE THREAD

**Issue by odcgit** [teppokoivula/ProcessLoginHistory#1]
Hi Teppo - thanks for the great module

In my setup for a site with membership - I set member user 'names' (not admins) with a numerical value to match their unique membership id for the organisation (not set within pw). 

Your module however logs users with a numerical 'name' as nonexistant, stores their $user->id as 0 and logs the login as a failure when it has been successful

Kind regards
Nik

**Comment by teppokoivula** [comment]
Thanks for reporting this @odcgit, latest commit seems to have fixed related issues :)

**Comment by odcgit** [comment]
Awesome - cheers.

Nik
