### ISSUE TITLE
Link to show user login history is now in modal but shows shows whole admin page

### ISSUE THREAD

**Issue by somatonic** [teppokoivula/ProcessLoginHistory#3]
![image](https://cloud.githubusercontent.com/assets/370148/6417300/d98f5d06-beac-11e4-828d-67e43014b4f5.png)

**Comment by teppokoivula** [comment]
This is a bit confusing, really; I can't seem to reproduce this issue, and no links to login history (to my best knowledge) should open in a modal window. In which situation exactly did this happen and do you have any idea why it opened in a modal? :)

Sorry if I'm missing something obvious here!

**Comment by somatonic** [comment]
Hmm I was just looking into this again and I think it was from the user edit screen. They open in a modal (lister) I think it was from that modal a link to the Login History, but I can't see that fieldset anymore when editing user (core). But I can see the Login History fieldset when I click on a user on the ProcessLoginHistory list. Strange thing is I can't see a "Delete" tab then, like when editing a user from the  core ProcessUser although it's the same edit screen (one modal one not).

**Comment by teppokoivula** [comment]
Thanks for clarifying, though it looks like I'm _still_ having trouble with this. In short, I can't get any links on the user edit screen to open in modal :)

Right now I'm guessing that you might be using ListerPro, as [modal edit windows are apparently one of it's features](https://processwire.com/api/modules/lister-pro/#listerpro-provides-modal-page-editing). I'll have to get my hands on one of those to debug this further, it seems.

**Comment by teppokoivula** [comment]
Closing some old issues. Looks like I was never able to reproduce this one, and since it hasn't been raised since I would assume that it's not a very common situation.
