### ISSUE TITLE
MyISAM restriction?

### ISSUE THREAD

**Issue by adrianbj** [teppokoivula/ProcessLoginHistory#7]
Hi @teppokoivula - would you mind removing the  `ENGINE = MYISAM` from the table creation process. On a managed DB I use, it isn't allowed so the module install failed until I removed that from the table creation on install.

Thanks.

**Comment by teppokoivula** [comment]
Hey @adrianbj! Removed. I can't think of any reason why MyISAM would've been necessary, but let me know if you notice any odd behaviour without it :)
