### ISSUE TITLE
Deprecations

### ISSUE THREAD

**Issue by matjazpotocnik** [teppokoivula/ProcessLoginHistory#8]
Hi Teppo!

PHP Deprecated: htmlentities(): Passing null to parameter #1 ($string) of type string is deprecated in /site/modules/ProcessLoginHistory/ProcessLoginHistory.module:562

Also fous looks a bit odd:

![image](https://user-images.githubusercontent.com/7663992/236524558-b14e2295-db31-49ab-a751-720ff9588639.png)

Also, I can't specify date from/to.

**Comment by teppokoivula** [comment]
Thanks @matjazpotocnik, deprecation notice and focus style should be fixed now.

I'm wondering if "I can't specify date from/to" is due to the input right before dates? Dates can only be selected when you've first selected "between" option there.

**Comment by matjazpotocnik** [comment]
I selected "between" option first and then clicked into "date_from" input field. Hovering over input says "Not relevant in this context".

![image](https://user-images.githubusercontent.com/7663992/236639426-623d4dab-5278-4548-8e25-95d2f6fb1a32.png)

Maybe we don't need info about flash?

**Comment by teppokoivula** [comment]
Sounds like something in the JS is not working as expected. Are you seeing any JS errors in the console?

Which version of ProcessWire is this on?

> Maybe we don't need info about flash?

Thought I'd removed this already. Removed now :)

**Comment by matjazpotocnik** [comment]
No JS errors. I'm on 3.0.217 and using $config->debug="dev" that loads latest version of jQuery. Will debug tomorrow to see if I can narrow it down.

**Comment by teppokoivula** [comment]
On latest dev branch version jQuery Migrate was complaining about the use of .attr() to get input value. That's now fixed, though it was working for me before as well so not positive this was it.

**Comment by matjazpotocnik** [comment]
Yes. it's jQuery...

**Comment by matjazpotocnik** [comment]
Ah, working now with the change to val(). Thanks.

Perhaps applying

form#filters .filter[disabled] {
    opacity: .5;
}

to the disabled date from/to inputs? As now visually disabled input is not clearly visible. Nice to see you care for a11y!
